package edu.egg.loquebusques.entidades;

public enum Localidad {
    ALBA_POSSE, ALICIA_ALTA, ALICIA_BAJA, ALMAFUERTE, APÓSTOLES, ARISTÓBULO_DEL_VALLE, ARROYO_DEL_MEDIO,
    AZARA, BARRA, CONCEPCIÓN, BARRIO_BERNARDINO, RIVADAVIA, BARRIO_DEL_LAGO, BARRIO_GUATAMBÚ, BARRIO_ITÁ, BARRIO_RURAL, BERNARDO_DE_IRIGOYEN, 
    BONPLAND, CAÁ_YARÍ, CAMIÓN_CUE, CAMPO_GRANDE, CAMPO_RAMÓN, CAMPO_VIERA, CANDELARIA, CAPIOVÍ, CAPIOVICIÑO, CARAGUATAY,
    CERRO_AZUL, CERRO_CORÁ, COLONIA_ALBERDI, COLONIA_ALICIA, COLONIA_APARECIDA, COLONIA_AURORA, COLONIA_DELICIA, 
    COLONIA_HELVECIA, COLONIA_POLANA, COLONIA_VICTORIA, COMANDANTE_ANDRESITO, CONCEPCIÓN_DE_LA_SIERRA, CORPUS_CHRISTI, 
    CRUCE_CABALLERO, DOMINGO_SAVIO, DOS_ARROYOS, DOS_DE_MAYO, DOS_HERMANAS, EL_ALCÁZAR, EL_PIÑALITO, EL_SALTO, EL_SOBERBIO, 
    ELDORADO, ESTACIÓN_APÓSTOLES, FACHINAL, FLORENTINO_AMEGHINO, FRACRÁN, GARUHAPÉ, GARUHAPÉ_MI_GENERAL_ALVEAR, GENERAL_URQUIZA, 
    GOBERNADOR_LANUSSE, GOBERNADOR_LÓPEZ, GOBERNADOR_ROCA, GUARANÍ, HIPÓLITO_YRIGOYEN, INTEGRACIÓN, ITACARUARÉ, JARDÍN_AMÉRICA,
    LA_CORITA, LAHARRAGUE, LEANDRO_N_ALEM, LORETO, LOS_HELECHOS, MÁRTIRES, MBOPICUÁ, MOJÓN_GRANDE, MONTECARLO, NEMESIO_PARMA, 
    NUEVE_DE_JULIO, KILÓMETRO_20, OASIS, OBERÁ, OLEGARIO, VÍCTOR_ANDRADE, PANAMBÍ, PANAMBÍ_KILÓMETRO_8, PARAJE_FONTANA, 
    PEÑÓN_DEL_TEYÚ_CUARÉ, PINDAPOY, PIRAY_KILÓMETRO_18, POZO_AZUL, PRIMERO_DE_MAYO, PROFUNDIDAD, PUEBLO_ILLIA, PUERTO_AZARA, 
    PUERTO_ESPERANZA, PUERTO_IGUAZÚ, PUERTO_LEONI, PUERTO_LIBERTAD, PUERTO_MADO, PUERTO_MINERAL, PUERTO_PINARES, PUERTO_PIRAY, 
    PUERTO_RICO, PUERTO_SANTA_ANA, RESERVA_NATURAL_DE_LA_DEFENSA_PUERTO_PENÍNSULA, ROCA_CHICA, RUIZ_DE_MONTOYA, SALTO_ENCANTADO,
    SAN_ALBERTO, SAN_ANTONIO, SAN_FRANCISCO_DE_ASÍS, SAN_GOTARDO, SAN_IGNACIO, SAN_JAVIER, SAN_JOSÉ, SAN_MARTÍN, SAN_PEDRO,
    SAN_VICENTE, SANTA_ANA, SANTA_MARÍA, SANTA_RITA, SANTIAGO_DE_LINIERS, SANTO_PIPÓ, TARUMÁ, TERCIADOS_PARAÍSO, 
    TOBUNA, TORTA_QUEMADA, TRES_CAPONES, VALLE_HERMOSO,VEINTICINCO_DE_MAYO, VILLA_AKERMAN, VILLA_BONITA, VILLA_LIBERTAD, VILLA_PARODI, 
    VILLA_ROULET, VILLA_SALTO_ENCANTADO, VILLALONGA, WANDA
}
